[package]
name = "astro-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
astro-core = { path = "../astro-core" }
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true

[lints]
workspace = true
